# -*- coding: utf-8 -*-
"""CIS 412

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTR4rXO30ooNahnBPlmDI1wqUASpzamG
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, classification_report
from sklearn.tree import plot_tree
 
st.title("NBA Rookie Longevity Prediction")
st.markdown("**CIS 412 Team Project | CRISP-DM Framework**")
 
# ── Data Loading ──────────────────────────────────────────────────────────────
st.header("1. Data Understanding")
 
df = pd.read_csv("nba_logreg (1).csv")
 
st.subheader("Raw Data (first 5 rows)")
st.write(df.head())
 
st.subheader("Data Types")
st.write(df.dtypes)
 
st.subheader("Statistical Summary")
st.write(df.describe().round(2))
 
st.subheader("Missing Values")
st.write(df.isnull().sum())
st.write(f"Total missing: {df.isnull().sum().sum()} (all in 3P% column)")
 
st.write(f"Duplicate rows: {df.duplicated().sum()}")
st.write(f"Duplicate player names: {df['Name'].duplicated().sum()}")
 
# Target distribution
target_counts = df['TARGET_5Yrs'].value_counts().sort_index()
st.subheader("Target Variable Distribution")
st.write(f"0 (did NOT last 5 yrs): {int(target_counts[0.0])}  ({target_counts[0.0]/len(df)*100:.1f}%)")
st.write(f"1 (lasted 5+ yrs):      {int(target_counts[1.0])}  ({target_counts[1.0]/len(df)*100:.1f}%)")
 
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
labels = ['Did NOT last\n5 years (0)', 'Lasted 5+\nyears (1)']
colors = ['#e74c3c', '#27ae60']
bars = axes[0].bar(labels, target_counts.values, color=colors, edgecolor='black', linewidth=0.7, width=0.55)
for bar, val in zip(bars, target_counts.values):
    axes[0].text(bar.get_x() + bar.get_width()/2, val + 12,
                 f'{int(val)}', ha='center', fontweight='bold', fontsize=12)
axes[0].set_ylabel('Number of Players')
axes[0].set_title('Target Variable — Count')
axes[1].pie(target_counts.values, labels=labels, colors=colors,
            autopct='%1.1f%%', startangle=90, textprops={'fontsize': 11},
            wedgeprops={'edgecolor': 'black', 'linewidth': 0.7})
axes[1].set_title('Target Variable — Proportion')
plt.suptitle('Is the Dataset Balanced?', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
st.pyplot(fig)
plt.clf()
 
# ── Data Preparation ──────────────────────────────────────────────────────────
st.header("2. Data Preparation")
 
st.subheader("Handling Missing Values")
st.write("The '3P%' column has 11 missing values. Imputing with column mean.")
df['3P%'] = df['3P%'].fillna(df['3P%'].mean())
st.write(df.isnull().sum())
 
st.subheader("Handling Duplicate Values")
df.drop_duplicates(inplace=True)
df.drop_duplicates(subset=['Name'], keep='first', inplace=True)
st.write(f"Duplicate rows after dropping: {df.duplicated().sum()}")
st.write(f"Duplicate player names after dropping: {df['Name'].duplicated().sum()}")
st.write(f"Dataset shape after cleaning: {df.shape}")
 
st.subheader("Correlation Matrix Visualization")
st.write("Visualizing the correlation matrix to understand feature relationships.")
numeric_df = df.drop(columns=['Name'])
corr_matrix = numeric_df.corr()
 
target_corr = corr_matrix['TARGET_5Yrs'].drop('TARGET_5Yrs').sort_values(ascending=True)
st.write("Correlation of each feature with TARGET_5Yrs (sorted):")
st.write(target_corr.round(3))
 
fig, ax = plt.subplots(figsize=(10, 7))
bar_colors = ['#27ae60' if v > 0 else '#e74c3c' for v in target_corr.values]
target_corr.plot(kind='barh', color=bar_colors, edgecolor='black', linewidth=0.5, ax=ax)
ax.set_title('Which Rookie Stats Correlate with Lasting 5+ Years?', fontweight='bold')
ax.set_xlabel('Correlation with TARGET_5Yrs')
ax.axvline(x=0, color='black', linewidth=0.8)
plt.tight_layout()
st.pyplot(fig)
plt.clf()
 
# Heatmap
fig, ax = plt.subplots(figsize=(14, 10))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', ax=ax)
ax.set_title('Correlation Heatmap', fontsize=14)
plt.tight_layout()
st.pyplot(fig)
plt.clf()
 
# ── Modeling ──────────────────────────────────────────────────────────────────
st.header("3. Modeling")
 
X = df.drop(['Name', 'TARGET_5Yrs'], axis=1)
y = df['TARGET_5Yrs']
X = X.fillna(X.mean())
 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
 
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
 
st.write("Data preparation and scaling complete.")
 
# Logistic Regression
st.subheader("Logistic Regression")
log_reg = LogisticRegression(random_state=42, solver='liblinear')
log_reg.fit(X_train_scaled, y_train)
y_pred_lr = log_reg.predict(X_test_scaled)
y_prob_lr = log_reg.predict_proba(X_test_scaled)[:, 1]
y_train_pred_lr = log_reg.predict(X_train_scaled)
 
st.write(f"**Train Accuracy:** {accuracy_score(y_train, y_train_pred_lr):.4f}")
st.write(f"**Test Accuracy:** {accuracy_score(y_test, y_pred_lr):.4f}")
st.write(f"**Precision:** {precision_score(y_test, y_pred_lr):.4f}")
st.write(f"**Recall:** {recall_score(y_test, y_pred_lr):.4f}")
st.write(f"**ROC AUC:** {roc_auc_score(y_test, y_prob_lr):.4f}")
st.text("Classification Report:\n" + classification_report(y_test, y_pred_lr))
 
# Random Forest
st.subheader("Random Forest Classifier")
rand_forest = RandomForestClassifier(random_state=42)
rand_forest.fit(X_train, y_train)
y_pred_rf = rand_forest.predict(X_test)
y_prob_rf = rand_forest.predict_proba(X_test)[:, 1]
y_train_pred_rf = rand_forest.predict(X_train)
 
st.write(f"**Train Accuracy:** {accuracy_score(y_train, y_train_pred_rf):.4f}")
st.write(f"**Test Accuracy:** {accuracy_score(y_test, y_pred_rf):.4f}")
st.write(f"**Precision:** {precision_score(y_test, y_pred_rf):.4f}")
st.write(f"**Recall:** {recall_score(y_test, y_pred_rf):.4f}")
st.write(f"**ROC AUC:** {roc_auc_score(y_test, y_prob_rf):.4f}")
st.text("Classification Report:\n" + classification_report(y_test, y_pred_rf))
 
# Decision Tree
st.subheader("Decision Tree Classifier")
dec_tree = DecisionTreeClassifier(random_state=42)
dec_tree.fit(X_train, y_train)
y_pred_dt = dec_tree.predict(X_test)
y_prob_dt = dec_tree.predict_proba(X_test)[:, 1]
y_train_pred_dt = dec_tree.predict(X_train)
 
st.write(f"**Train Accuracy:** {accuracy_score(y_train, y_train_pred_dt):.4f}")
st.write(f"**Test Accuracy:** {accuracy_score(y_test, y_pred_dt):.4f}")
st.write(f"**Precision:** {precision_score(y_test, y_pred_dt):.4f}")
st.write(f"**Recall:** {recall_score(y_test, y_pred_dt):.4f}")
st.write(f"**ROC AUC:** {roc_auc_score(y_test, y_prob_dt):.4f}")
st.text("Classification Report:\n" + classification_report(y_test, y_pred_dt))
 
st.subheader("Decision Tree Visualization")
fig, ax = plt.subplots(figsize=(30, 20))
plot_tree(dec_tree, filled=True, feature_names=X.columns, class_names=['< 5 Years', '5+ Years'], ax=ax)
ax.set_title('Decision Tree Visualization (Full Tree)', fontsize=20)
st.pyplot(fig)
plt.clf()
 
# ── Evaluation ────────────────────────────────────────────────────────────────
st.header("4. Evaluation")
 
st.subheader("Model Performance Comparison")
metrics = {
    'Logistic Regression': {
        'Accuracy': accuracy_score(y_test, y_pred_lr),
        'Precision': precision_score(y_test, y_pred_lr),
        'Recall': recall_score(y_test, y_pred_lr),
        'ROC AUC': roc_auc_score(y_test, y_prob_lr)
    },
    'Random Forest': {
        'Accuracy': accuracy_score(y_test, y_pred_rf),
        'Precision': precision_score(y_test, y_pred_rf),
        'Recall': recall_score(y_test, y_pred_rf),
        'ROC AUC': roc_auc_score(y_test, y_prob_rf)
    },
    'Decision Tree': {
        'Accuracy': accuracy_score(y_test, y_pred_dt),
        'Precision': precision_score(y_test, y_pred_dt),
        'Recall': recall_score(y_test, y_pred_dt),
        'ROC AUC': roc_auc_score(y_test, y_prob_dt)
    }
}
 
metrics_df = pd.DataFrame(metrics).T
st.write(metrics_df.round(4))
 
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
axes = axes.flatten()
metric_names = ['Accuracy', 'Precision', 'Recall', 'ROC AUC']
colors = sns.color_palette('viridis', n_colors=3)
 
for i, metric in enumerate(metric_names):
    metrics_df[metric].plot(kind='bar', ax=axes[i], color=colors, edgecolor='black')
    axes[i].set_title(f'{metric} Comparison', fontsize=14)
    axes[i].set_ylabel(metric)
    axes[i].tick_params(axis='x', rotation=45)
    axes[i].grid(axis='y', linestyle='--', alpha=0.7)
    for p in axes[i].patches:
        axes[i].annotate(f'{p.get_height():.3f}',
                         (p.get_x() + p.get_width() / 2., p.get_height()),
                         ha='center', va='center', xytext=(0, 10), textcoords='offset points')
 
plt.suptitle('Comparison of Classification Model Performance', fontsize=18, y=1.02)
plt.tight_layout(rect=[0, 0.03, 1, 0.98])
st.pyplot(fig)
plt.clf()
 
st.subheader("Overfitting Analysis")
st.write("Decision Tree: Train accuracy is near 1.0 vs test ~0.63 — clear overfitting.")
st.write("Logistic Regression: Minimal gap between train and test — generalizes well.")
st.write("Random Forest: Slight overfit but much better than raw Decision Tree.")
 
st.subheader("Feature Importance (Random Forest)")
feature_importances = rand_forest.feature_importances_
features_df = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importances})
features_df = features_df.sort_values(by='Importance', ascending=False)
st.write(features_df.head(10))
 
fig, ax = plt.subplots(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=features_df, palette='viridis',
            hue='Feature', legend=False, ax=ax)
ax.set_title('Feature Importances from Random Forest Classifier', fontsize=16)
ax.set_xlabel('Importance', fontsize=12)
ax.set_ylabel('Feature', fontsize=12)
plt.tight_layout()
st.pyplot(fig)
plt.clf()
 
# ── Deployment ────────────────────────────────────────────────────────────────
st.header("5. Deployment")
st.write("""
**How the model will be deployed:**
- Logistic Regression is the best performing model (highest accuracy + ROC AUC).
- It can be deployed as a scouting tool for NBA front offices to evaluate rookies after their first season.
- Input: rookie season stats. Output: probability of lasting 5+ years in the league.
 
**Ethical Considerations:**
- The model should not be the sole decision-maker — human judgment must remain central.
- Historical bias in the data (e.g., era differences) may affect predictions for modern players.
- Players from underrepresented backgrounds should not be disadvantaged by biased training data.
 
**Risks & Mitigation:**
- Overfitting risk (especially Decision Tree) — mitigated by using Logistic Regression as primary model.
- Data drift over time — model should be retrained periodically with new seasons of data.
- Small dataset (~1300 players) — predictions may be less reliable for edge-case players.
""")
 
